package app.funput.funput.ui.about.licenses

import android.content.Context
import androidx.annotation.StringRes
import app.funput.funput.R

/** A third-party notice shipped as an asset, and what to call it on screen. */
internal data class LicenseNotice(
    @param:StringRes val title: Int,
    val assetPath: String,
) {
    /** Markdown notices are parsed as such; plain-text licences keep their layout. */
    val isMarkdown: Boolean get() = assetPath.endsWith(".md")
}

/**
 * Shown in this order: the dictionary's notice (generated by `:ime`), then the licences of
 * FunputUI's bundled Be Vietnam Pro font and Phosphor icons.
 */
internal val LicenseNotices = listOf(
    LicenseNotice(R.string.licenses_dictionary, "lexicon/NOTICE.md"),
    LicenseNotice(R.string.licenses_font, "licenses/be-vietnam-pro-OFL.txt"),
    LicenseNotice(R.string.licenses_icons, "licenses/phosphor-MIT.txt"),
)

/** Reads [notice]'s text, or null when the asset cannot be read. Blocking: call off the main thread. */
internal fun Context.readNotice(notice: LicenseNotice): String? = runCatching {
    assets.open(notice.assetPath).bufferedReader().use { it.readText() }
}.getOrNull()
