/* Generated by cbindgen — do not edit. Regenerate: scripts/gen-header.sh */

#ifndef FUNPUT_H
#define FUNPUT_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * No remembered state for this app — the host should leave the composition
 * engine's current VI/EN state untouched.
 */
#define APP_LANG_UNKNOWN -1

/**
 * The app is remembered as English (Vietnamese input suppressed).
 */
#define APP_LANG_ENGLISH 0

/**
 * The app is remembered as Vietnamese.
 */
#define APP_LANG_VIETNAMESE 1

#if defined(FUNPUT_CHARSET)
/**
 * [`funput_charset_detect`] when the evidence does not pick a charset out — the
 * text is ASCII, or reads the same under every candidate. Not an error.
 */
#define FUNPUT_CHARSET_UNKNOWN -1
#endif

#if defined(FUNPUT_CONVERT)
#define FUNPUT_CONVERT_MODE_EMPTY 0
#endif

#if defined(FUNPUT_CONVERT)
#define FUNPUT_CONVERT_MODE_TEXT 1
#endif

#if defined(FUNPUT_CONVERT)
#define FUNPUT_CONVERT_MODE_FILES 2
#endif

#if defined(FUNPUT_CONVERT)
#define FUNPUT_CONVERT_UNKNOWN -1
#endif

/**
 * [`funput_process_key`] source: main keyboard — digits may act as VNI modifiers.
 */
#define SOURCE_STANDARD 0

/**
 * [`funput_process_key`] source: numeric keypad — a digit is always a literal number.
 */
#define SOURCE_NUMPAD 1

#define METHOD_TELEX 0

#define METHOD_VNI 1

#define METHOD_TELEX_ADVANCED 2

/**
 * Max output codepoints carried inline. Generous enough for English-restore of
 * long words; longer output is truncated (practically never happens).
 */
#define CHARS_CAP 64

/**
 * Platform action: `0 = None`, `1 = Send`, `2 = Restore`.
 */
#define ACTION_NONE 0

#define ACTION_SEND 1

#define ACTION_RESTORE 2

#define SUGGESTION_CAP 3

#define SUGGESTION_CHARS_CAP 32

/**
 * Opaque per-app VI/EN memory handle, independent of [`crate::FunputEngine`] —
 * it only decides "should this app be Vietnamese", never touches composition.
 * A single-owner handle: create with [`funput_app_language_new`], release with
 * [`funput_app_language_free`].
 */
typedef struct FunputAppLanguage FunputAppLanguage;

#if defined(FUNPUT_CONVERT)
typedef struct FunputConvertJob FunputConvertJob;
#endif

#if defined(FUNPUT_CONVERT)
typedef struct FunputConvertScan FunputConvertScan;
#endif

#if defined(FUNPUT_CONVERT)
typedef struct FunputConvertSession FunputConvertSession;
#endif

/**
 * Opaque IME engine handle for C callers. Create with [`funput_engine_new`],
 * release with [`funput_engine_free`]. cbindgen emits this as an opaque struct.
 */
typedef struct FunputEngine FunputEngine;

/**
 * Opaque, single-owner personal suggestion handle. It is independent from the
 * Vietnamese composition engine and must be driven from a serial worker.
 */
typedef struct FunputSuggestionEngine FunputSuggestionEngine;

#if defined(FUNPUT_CHARSET)
/**
 * What a conversion produced. POD, returned by value — nothing is allocated and
 * there is nothing to free.
 *
 * The two counters are separate because the problems are: `unmapped` is text that
 * came out **wrong or guessed at**, and is the number worth putting in front of a
 * user. `normalized` is text understood exactly whose spelling changed — converting
 * to Unicode tổ hợp changes every toned vowel and none of it is a loss.
 */
typedef struct {
    /**
     * Codepoints the conversion produced, whether or not they fit in `out`.
     */
    uintptr_t len;
    /**
     * Characters the target charset could not represent, or represented by
     * guessing. Non-zero means the result is worth showing the user before use.
     */
    uintptr_t unmapped;
    /**
     * Characters understood exactly whose spelling the target charset writes
     * differently. Not a loss, and converting back returns the original.
     */
    uintptr_t normalized;
} FunputConversion;
#endif

#if defined(FUNPUT_CONVERT)
typedef struct {
    uint8_t mode;
    uintptr_t target;
    int32_t source;
    bool from_file;
    bool has_input_preview;
    uintptr_t rows_first;
    uintptr_t rows_count;
    uintptr_t rows_total;
    uintptr_t ready;
    uintptr_t unreadable_count;
} FunputConvertView;
#endif

#if defined(FUNPUT_CONVERT)
typedef struct {
    int32_t source;
} FunputConvertRow;
#endif

/**
 * Result of one keystroke, returned by value (POD, no allocation, no free).
 *
 * `chars[0..count]` are the output codepoints (UTF-32) to inject after deleting
 * `backspace` characters. For `action == ACTION_NONE`, `count == 0`.
 */
typedef struct {
    uint8_t action;
    uint32_t backspace;
    uint32_t count;
    uint32_t chars[CHARS_CAP];
} FunputResult;

/**
 * A whole engine configuration passed by value over the C ABI — the six user
 * options. `enabled` and the gõ tắt shortcut table have their own functions.
 */
typedef struct {
    /**
     * `0 = Telex`, `1 = VNI`, `2 = Telex Advanced` (see `METHOD_*`).
     */
    uint8_t method;
    /**
     * `0 = Traditional`, `1 = Modern`.
     */
    uint8_t tone_style;
    bool smart_restore;
    bool eager_restore;
    bool spell_check;
    bool auto_capitalize;
} FunputConfig;

typedef struct {
    uint32_t count;
    uint32_t chars[SUGGESTION_CHARS_CAP];
} FunputSuggestionCandidate;

typedef struct {
    uint32_t count;
    FunputSuggestionCandidate candidates[SUGGESTION_CAP];
} FunputSuggestionResult;

typedef struct {
    uint32_t words;
    uint32_t promoted_words;
    uint32_t exact_nodes;
    uint32_t folded_nodes;
    uint32_t pending_mutations;
    uint64_t journal_bytes;
    uint64_t estimated_heap_bytes;
    uint64_t last_snapshot_bytes;
} FunputSuggestionStats;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Look up the remembered VI/EN state for the just-focused app `id`. Returns
 * [`super::APP_LANG_VIETNAMESE`] / [`super::APP_LANG_ENGLISH`] when this app has
 * a remembered choice, [`super::APP_LANG_UNKNOWN`] otherwise — the host should
 * only call `funput_set_enabled` in the former case, leaving the composition
 * engine's current state untouched for an app it has never seen toggled.
 *
 * # Safety
 * `id` must point to at least `id_len` readable bytes, or be null.
 */
int32_t funput_app_language_note_focus(const FunputAppLanguage *handle,
                                       const uint8_t *id,
                                       uintptr_t id_len);

/**
 * Record a manual VI/EN toggle for the app the caller knows is currently
 * focused (e.g. a hotkey pressed while that app has focus). Returns `true` on
 * success — the host should then persist `(id, enabled)` to its own settings
 * store, since this engine never touches disk.
 *
 * A toggle initiated from a surface that steals focus (a tray icon, the
 * Settings window) is a platform-side concern: resolve the target app id
 * there before calling this, the same way the per-app `pending`/deferred
 * overrides already work today.
 *
 * # Safety
 * `id` must point to at least `id_len` readable bytes, or be null.
 */
bool funput_app_language_note_toggle(FunputAppLanguage *handle,
                                     const uint8_t *id,
                                     uintptr_t id_len,
                                     bool enabled);

/**
 * Create an empty per-app memory. Release it with [`funput_app_language_free`].
 */
FunputAppLanguage *funput_app_language_new(void);

/**
 * Free a handle created by [`funput_app_language_new`]. Null is ignored.
 *
 * # Safety
 * `handle` must come from [`funput_app_language_new`] and not be freed already.
 */
void funput_app_language_free(FunputAppLanguage *handle);

/**
 * Load one remembered `(id, enabled)` pair — the host calls this once per row
 * read from its own settings file at startup, mirroring
 * [`crate::funput_add_shortcut`]. An empty or invalid `id` is ignored.
 *
 * # Safety
 * `id` must point to at least `id_len` readable bytes, or be null.
 */
bool funput_app_language_seed(FunputAppLanguage *handle,
                              const uint8_t *id,
                              uintptr_t id_len,
                              bool enabled);

/**
 * Forget every remembered app — a full reset.
 *
 * # Safety
 * `handle` must come from [`super::funput_app_language_new`] or be null.
 */
void funput_app_language_clear(FunputAppLanguage *handle);

/**
 * Forget one app. Returns `true` if an entry was removed.
 *
 * # Safety
 * `id` must point to at least `id_len` readable bytes, or be null.
 */
bool funput_app_language_forget(FunputAppLanguage *handle, const uint8_t *id, uintptr_t id_len);

#if defined(FUNPUT_CHARSET)
/**
 * How many charsets there are. Valid indices run `0..funput_charset_count()`.
 */
uintptr_t funput_charset_count(void);
#endif

#if defined(FUNPUT_CHARSET)
/**
 * Write the display name of the charset at `index` into `out` as UTF-32, returning
 * its length in codepoints. An index out of range gives 0.
 *
 * The name comes from core so that two platforms' menus cannot drift apart. It is
 * the encoding's own name (`TCVN3 (ABC)`, `VNI-Windows`), which reads the same in
 * any interface language.
 *
 * Sizing works the same way as [`funput_charset_convert`]: the length is returned
 * whether or not it fit, and nothing is written unless all of it fits.
 *
 * # Safety
 * `out` must point to at least `cap` writable `u32` values, or be null.
 */
uintptr_t funput_charset_name(uintptr_t index, uint32_t *out, uintptr_t cap);
#endif

#if defined(FUNPUT_CHARSET)
/**
 * Convert UTF-32 `text` from one charset to another, writing the result into `out`.
 *
 * `from` and `to` are indices into the charset list — see the module doc. Either
 * one out of range yields a zeroed [`FunputConversion`], as does a panic anywhere
 * inside.
 *
 * # Sizing
 *
 * `len` is the length of the result whether or not it fit, and **nothing is written
 * unless all of it fits**. So a host either guesses a buffer generously and is done
 * in one call, or passes `out = NULL, cap = 0` to learn the length and calls again.
 * A conversion is not always shorter than its input: VNI-Windows spells most toned
 * letters as two characters, so a guess of `text_len` is not enough.
 *
 * `unmapped` and `normalized` are filled in on the sizing call too, so a host can
 * warn about what will be lost before it allocates anything.
 *
 * `from` must be what the text actually **is**; guessing it is
 * [`funput_charset_detect`](super::funput_charset_detect)'s job, not this one's.
 *
 * # Safety
 * `text` must point to at least `text_len` readable `u32` values, or be null.
 * `out` must point to at least `cap` writable `u32` values, or be null.
 */
FunputConversion funput_charset_convert(const uint32_t *text,
                                        uintptr_t text_len,
                                        uintptr_t from,
                                        uintptr_t to,
                                        uint32_t *out,
                                        uintptr_t cap);
#endif

#if defined(FUNPUT_CHARSET)
/**
 * Guess which charset `text` is written in. Returns an index into the charset
 * list, or [`FUNPUT_CHARSET_UNKNOWN`] when the evidence does not pick one out.
 *
 * `FUNPUT_CHARSET_UNKNOWN` is not a failure and covers three honest situations: no
 * evidence at all (ASCII, digits), a genuine tie between charsets that spell this
 * text the same way, and text that reads identically under every one of them. A
 * host should offer the user the list rather than treat it as an error.
 *
 * Detection reads a prefix rather than a whole document, so passing the whole text
 * costs nothing. A host that detects on a prefix and converts the whole thing is
 * doing the right thing.
 *
 * # Safety
 * `text` must point to at least `text_len` readable `u32` values, or be null.
 */
int32_t funput_charset_detect(const uint32_t *text, uintptr_t text_len);
#endif

#if defined(FUNPUT_CONVERT)
FunputConvertSession *funput_convert_session_new(void);
#endif

#if defined(FUNPUT_CONVERT)
/**
 * # Safety
 * `session` must be a live handle returned by `funput_convert_session_new`, or null.
 */
void funput_convert_session_free(FunputConvertSession *session);
#endif

#if defined(FUNPUT_CONVERT)
void funput_convert_session_reset(FunputConvertSession *session);
#endif

#if defined(FUNPUT_CONVERT)
void funput_convert_session_refresh(FunputConvertSession *session);
#endif

#if defined(FUNPUT_CONVERT)
void funput_convert_session_set_target(FunputConvertSession *session, uintptr_t index);
#endif

#if defined(FUNPUT_CONVERT)
void funput_convert_session_pick_source(FunputConvertSession *session, int32_t index);
#endif

#if defined(FUNPUT_CONVERT)
void funput_convert_session_pick_row_source(FunputConvertSession *session,
                                            uintptr_t row,
                                            int32_t index);
#endif

#if defined(FUNPUT_CONVERT)
void funput_convert_session_set_row_window(FunputConvertSession *session,
                                           uintptr_t first,
                                           uintptr_t len);
#endif

#if defined(FUNPUT_CONVERT)
FunputConvertView funput_convert_session_view(const FunputConvertSession *session);
#endif

#if defined(FUNPUT_CONVERT)
FunputConvertRow funput_convert_session_row(const FunputConvertSession *session, uintptr_t index);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_session_out_dir(const FunputConvertSession *session,
                                         uint32_t *out,
                                         uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
void funput_convert_session_set_input(FunputConvertSession *session,
                                      const uint32_t *text,
                                      uintptr_t len);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_session_output_preview(const FunputConvertSession *session,
                                                uint32_t *out,
                                                uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_session_warning(const FunputConvertSession *session,
                                         uint32_t *out,
                                         uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_session_file_name(const FunputConvertSession *session,
                                           uint32_t *out,
                                           uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_session_input_preview(const FunputConvertSession *session,
                                               uint32_t *out,
                                               uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_session_unreadable_line(const FunputConvertSession *session,
                                                 uint32_t *out,
                                                 uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_session_row_name(const FunputConvertSession *session,
                                          uintptr_t index,
                                          uint32_t *out,
                                          uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_session_row_note(const FunputConvertSession *session,
                                          uintptr_t index,
                                          uint32_t *out,
                                          uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_session_result_text(const FunputConvertSession *session,
                                             uint32_t *out,
                                             uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_session_save_bytes(const FunputConvertSession *session,
                                            uint8_t *out,
                                            uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
FunputConvertScan *funput_convert_scan_new(void);
#endif

#if defined(FUNPUT_CONVERT)
bool funput_convert_scan_add_path(FunputConvertScan *scan, const uint8_t *path, uintptr_t len);
#endif

#if defined(FUNPUT_CONVERT)
bool funput_convert_scan_run(FunputConvertScan *scan);
#endif

#if defined(FUNPUT_CONVERT)
bool funput_convert_session_adopt_scan(FunputConvertSession *session, FunputConvertScan *scan);
#endif

#if defined(FUNPUT_CONVERT)
void funput_convert_scan_free(FunputConvertScan *scan);
#endif

#if defined(FUNPUT_CONVERT)
FunputConvertJob *funput_convert_job_new(const FunputConvertSession *session);
#endif

#if defined(FUNPUT_CONVERT)
bool funput_convert_job_run(FunputConvertJob *job);
#endif

#if defined(FUNPUT_CONVERT)
uintptr_t funput_convert_job_report(const FunputConvertJob *job, uint32_t *out, uintptr_t cap);
#endif

#if defined(FUNPUT_CONVERT)
void funput_convert_job_free(FunputConvertJob *job);
#endif

/**
 * Create a new engine. Release it with [`funput_engine_free`].
 */
FunputEngine *funput_engine_new(void);

/**
 * Free an engine created by [`funput_engine_new`]. Null is ignored.
 *
 * # Safety
 * `engine` must come from [`funput_engine_new`] and not be freed already.
 */
void funput_engine_free(FunputEngine *engine);

/**
 * Arm capitalization for the next word — call on text-field focus so the first
 * letter typed (start of input) is capitalized. A no-op unless auto-capitalize is on.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_arm_capitalization(FunputEngine *engine);

/**
 * Reset composition state (buffer + raw keys), e.g. on focus change.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_clear(FunputEngine *engine);

/**
 * Process one Unicode scalar from the main keyboard — [`funput_process_key`] with
 * [`SOURCE_STANDARD`]. A null handle or invalid `codepoint` yields
 * [`FunputResult::none`].
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
FunputResult funput_process_char(FunputEngine *engine, uint32_t codepoint);

/**
 * Process one Unicode scalar tagged with the physical key `source`
 * ([`SOURCE_STANDARD`] or [`SOURCE_NUMPAD`]). Returns the platform instruction by
 * value.
 *
 * A numpad digit (`SOURCE_NUMPAD` + `0`–`9`) is emitted as a literal number and
 * ends the current word instead of applying a VNI tone/shape. A null handle or
 * invalid `codepoint` yields [`FunputResult::none`]; an unknown `source` is
 * treated as [`SOURCE_STANDARD`].
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
FunputResult funput_process_key(FunputEngine *engine, uint32_t codepoint, uint32_t source);

/**
 * Copy the current composed buffer (the text the host shows as marked/underlined
 * composition) as UTF-32 into `out`, up to `cap` codepoints. Returns the number
 * of codepoints written.
 *
 * Null-safe: a null handle or null `out` yields `0`.
 *
 * # Safety
 * `engine` must be a valid handle or null. `out` must point to writable storage
 * for at least `cap` `u32` values, or be null.
 */
uintptr_t funput_buffer(const FunputEngine *engine, uint32_t *out, uintptr_t cap);

/**
 * Backspace inside the current composition: drop the last composed character so the
 * next keystroke composes against the corrected text (`Phua` ⌫ `s` → `Phú`). Returns a
 * no-op result — the host passes the Backspace through to delete its own character.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
FunputResult funput_backspace(FunputEngine *engine);

/**
 * Flip the word being composed between its Vietnamese form and its raw keystrokes
 * (`card` ⇄ `cải`), and back on a second call. Returns the delete+inject the host
 * should apply (`ACTION_SEND`), or [`FunputResult::none`] when there is nothing to
 * flip. Hosts that show marked text can ignore the payload and re-render
 * [`funput_buffer`] after a non-`ACTION_NONE` result.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
FunputResult funput_flip_composing(FunputEngine *engine);

/**
 * Re-open an already-committed word as the live composition, so the next keystroke
 * edits it (Backspace back onto `chào`, then `s` gives `cháo`). `word` is UTF-32, as in
 * [`funput_add_shortcut`](crate::funput_add_shortcut). Returns whether it was taken — only
 * a Vietnamese syllable is, so leave the document alone on `false`.
 *
 * # Safety
 * `engine` must be a valid handle or null; `word` must point to `len` `u32` values or
 * be null.
 */
bool funput_adopt(FunputEngine *engine, const uint32_t *word, uintptr_t len);

/**
 * Set the input method: `0 = Telex`, `1 = VNI`, `2 = Telex Advanced`.
 * Any other value falls back to standard Telex.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_set_method(FunputEngine *engine, uint8_t method);

/**
 * Apply a whole [`FunputConfig`] at once — the batch equivalent of the individual
 * `funput_set_*` functions, with the same side effects (a method change clears the
 * composition; auto-capitalize off resets its tracking). `funput_set_enabled` and
 * the shortcut table are separate and left untouched.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_configure(FunputEngine *engine, FunputConfig config);

/**
 * Enable or disable Vietnamese composition.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_set_enabled(FunputEngine *engine, bool enabled);

/**
 * Define a text-expansion shortcut (gõ tắt): typing `trigger` then a word boundary
 * injects `expansion` (`vn` → `Việt Nam`). Both strings are passed as UTF-32
 * (`*const u32` + length), matching [`crate::funput_buffer`]. An empty trigger is
 * ignored by the engine; re-adding a trigger overwrites it.
 *
 * Hosts sync the whole table by calling [`funput_clear_shortcuts`] then adding each
 * entry (the engine is a runtime mirror of the host's config).
 *
 * Null-safe: a null handle does nothing. A null `trigger`/`expansion` pointer is
 * treated as an empty string.
 *
 * # Safety
 * `engine` must be a valid handle or null. `trigger` must point to at least
 * `trigger_len` `u32` values (or be null), and `expansion` to at least
 * `expansion_len` `u32` values (or be null).
 */
void funput_add_shortcut(FunputEngine *engine,
                         const uint32_t *trigger,
                         uintptr_t trigger_len,
                         const uint32_t *expansion,
                         uintptr_t expansion_len);

/**
 * Remove every text-expansion shortcut. Combine with [`funput_add_shortcut`] to
 * replace the whole table when syncing from config.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_clear_shortcuts(FunputEngine *engine);

FunputSuggestionEngine *funput_suggestion_engine_new_in_memory(void);

/**
 * Open a local store from a UTF-8 path. Failure returns null without logging.
 *
 * # Safety
 * `path` must point to `path_len` readable bytes, or be null.
 */
FunputSuggestionEngine *funput_suggestion_engine_open(const uint8_t *path, uintptr_t path_len);

/**
 * # Safety
 * `engine` must be a live suggestion handle or null.
 */
void funput_suggestion_engine_free(FunputSuggestionEngine *engine);

/**
 * Record one completed UTF-32 token. Returns false for invalid input or failure.
 *
 * # Safety
 * `token` must point to `token_len` readable codepoints, or be null.
 */
bool funput_suggestion_learn(FunputSuggestionEngine *engine,
                             const uint32_t *token,
                             uintptr_t token_len);

/**
 * Return at most three UTF-32 candidates by value. Any failure returns empty.
 *
 * # Safety
 * `prefix` must point to `prefix_len` readable codepoints, or be null.
 */
FunputSuggestionResult funput_suggestion_query(const FunputSuggestionEngine *engine,
                                               const uint32_t *prefix,
                                               uintptr_t prefix_len);

/**
 * Flush pending learned tokens to the journal.
 *
 * # Safety
 * `engine` must be a live suggestion handle or null and may not be used concurrently.
 */
bool funput_suggestion_flush(FunputSuggestionEngine *engine);

/**
 * Replace the journal with a compact crash-safe snapshot.
 *
 * # Safety
 * `engine` must be a live suggestion handle or null and may not be used concurrently.
 */
bool funput_suggestion_compact(FunputSuggestionEngine *engine);

/**
 * Remove all learned words from memory and local persistence.
 *
 * # Safety
 * `engine` must be a live suggestion handle or null and may not be used concurrently.
 */
bool funput_suggestion_reset(FunputSuggestionEngine *engine);

/**
 * Return counters and byte estimates without exposing learned text.
 *
 * # Safety
 * `engine` must be a live suggestion handle or null and may not be used concurrently.
 */
FunputSuggestionStats funput_suggestion_stats(const FunputSuggestionEngine *engine);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FUNPUT_H */
