#!/usr/bin/env python3
"""Import the Phosphor icons listed in funput-ui/icons.txt as Android vector drawables.

Phosphor (https://phosphoricons.com, MIT) is FunputUI's icon set: SF Symbols may not ship on
Android, and Phosphor's rounded, even strokes are the closest open match. The release is pinned,
so running this again reproduces the committed drawables byte for byte; changing PHOSPHOR_TAG is
a deliberate, reviewable upgrade.

Usage (from platforms/android):  python3 scripts/import-phosphor-icons.py
"""
from pathlib import Path
import sys
import urllib.request
import xml.etree.ElementTree as ET

PHOSPHOR_TAG = "v2.0.8"
SOURCE = "https://raw.githubusercontent.com/phosphor-icons/core/{tag}/assets/{weight}/{file}.svg"
WEIGHTS = ("regular", "bold", "fill")
SVG_NS = "{http://www.w3.org/2000/svg}"
ANDROID_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ANDROID_ROOT / "funput-ui/icons.txt"
OUTPUT = ANDROID_ROOT / "funput-ui/src/main/res/drawable"
PREFIX = "ph_"


class IconError(ValueError):
    """An SVG this importer cannot turn into a vector drawable faithfully."""


def read_manifest(text):
    """Parse `name weight` lines, skipping blanks and # comments; weight defaults to regular."""
    entries = []
    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        weight = parts[1] if len(parts) > 1 else "regular"
        if len(parts) > 2 or weight not in WEIGHTS:
            raise IconError(f"icons.txt:{number}: expected '<name> [{'|'.join(WEIGHTS)}]'")
        entries.append((parts[0], weight))
    return entries


def resource_name(name, weight):
    """`gear-six` + `fill` -> `ph_gear_six_fill`; regular icons carry no weight suffix."""
    suffix = "" if weight == "regular" else f"_{weight}"
    return PREFIX + name.replace("-", "_") + suffix


def svg_to_vector(svg, label):
    """Convert one Phosphor SVG (paths only, 256x256 viewBox) into vector drawable XML."""
    root = ET.fromstring(svg)
    if root.get("viewBox") != "0 0 256 256":
        raise IconError(f"{label}: unexpected viewBox {root.get('viewBox')!r}")
    paths = []
    for element in root.iter():
        tag = element.tag.replace(SVG_NS, "")
        if tag == "svg":
            continue
        if tag != "path" or not element.get("d"):
            raise IconError(f"{label}: unsupported element <{tag}>; only <path d> is converted")
        paths.append(element.get("d"))
    if not paths:
        raise IconError(f"{label}: no paths")
    body = "".join(
        f'    <path\n        android:fillColor="#FF000000"\n        android:pathData="{d}" />\n'
        for d in paths
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"<!-- Phosphor {label}, {PHOSPHOR_TAG}, MIT. "
        "Generated by scripts/import-phosphor-icons.py; do not edit. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n    android:height="24dp"\n'
        '    android:viewportWidth="256"\n    android:viewportHeight="256">\n'
        f"{body}</vector>\n"
    )


def fetch(name, weight):
    file = name if weight == "regular" else f"{name}-{weight}"
    url = SOURCE.format(tag=PHOSPHOR_TAG, weight=weight, file=file)
    with urllib.request.urlopen(url, timeout=30) as response:
        return response.read().decode("utf-8")


def main():
    entries = read_manifest(MANIFEST.read_text())
    wanted = set()
    for name, weight in entries:
        resource = resource_name(name, weight)
        wanted.add(resource)
        vector = svg_to_vector(fetch(name, weight), f'"{name}" ({weight})')
        (OUTPUT / f"{resource}.xml").write_text(vector)
    stale = [p for p in OUTPUT.glob(f"{PREFIX}*.xml") if p.stem not in wanted]
    for path in stale:
        path.unlink()
    print(f"Imported {len(wanted)} Phosphor icons ({PHOSPHOR_TAG}); removed {len(stale)} stale.")


if __name__ == "__main__":
    try:
        main()
    except IconError as error:
        sys.exit(str(error))
