// RAII C++ wrapper around the `funput-ffi` C ABI (crates/funput-ffi/include/funput.h).
// Mirrors macOS's FunputComposer.swift: owns one opaque `FunputEngine*`, feeds it
// UTF-32 scalars, and decodes the composed buffer back to UTF-8 for Fcitx5/IBus.
//
// UTF-8 marshalling lives in ffi/utf8.h; `configure` takes a whole [Settings] so both
// shells share one mapping instead of restating every option (add a new engine
// option in `engineConfig` below and both Fcitx5 and IBus pick it up).

#ifndef FUNPUT_FFI_HANDLE_H
#define FUNPUT_FFI_HANDLE_H

#include <cstdint>
#include <string>
#include <vector>

#include "funput.h" // generated by cbindgen; on the include path via CMake
#include "settings/settings.h"
#include "ffi/utf8.h"

namespace funput {

// Physical origin of a key, mirroring funput-engine's `KeySource`. A numpad digit
// is tagged Numpad so the engine keeps it a literal number instead of composing a
// VNI tone/shape modifier. Values match the C `SOURCE_*` constants in funput.h.
enum class KeySource : uint32_t {
    Standard = SOURCE_STANDARD,
    Numpad = SOURCE_NUMPAD,
};

// The engine-affecting options of `settings`, as the C ABI's by-value config. The
// runtime VI/EN state is deliberately absent: that is the live toggle
// (`setEnabled`), not a persisted engine option.
inline FunputConfig engineConfig(const Settings &s) {
    return FunputConfig{
        static_cast<uint8_t>(s.method),
        static_cast<uint8_t>(s.toneStyle),
        s.smartRestore,
        s.eagerRestore,
        s.spellCheck,
        s.autoCapitalize,
    };
}

// Owns the engine handle; non-copyable, movable.
class Handle {
public:
    Handle() : engine_(funput_engine_new()) {}
    ~Handle() { funput_engine_free(engine_); }

    Handle(const Handle &) = delete;
    Handle &operator=(const Handle &) = delete;
    Handle(Handle &&o) noexcept : engine_(o.engine_) { o.engine_ = nullptr; }
    Handle &operator=(Handle &&o) noexcept {
        if (this != &o) {
            funput_engine_free(engine_);
            engine_ = o.engine_;
            o.engine_ = nullptr;
        }
        return *this;
    }

    // Apply every engine option in one FFI call. Same side effects the individual
    // setters had: a method change clears the composition, and turning
    // auto-capitalize off resets its tracking.
    void configure(const Settings &s) { funput_configure(engine_, engineConfig(s)); }
    void setEnabled(bool on) { funput_set_enabled(engine_, on); }
    void armCapitalization() { funput_arm_capitalization(engine_); }
    void clear() { funput_clear(engine_); }

    // Text-expansion shortcuts (gõ tắt). Replace the whole table by clearing then
    // re-adding each entry (the engine is a runtime mirror of settings.json).
    void clearShortcuts() { funput_clear_shortcuts(engine_); }
    void addShortcut(const std::string &trigger, const std::string &expansion) {
        const std::vector<uint32_t> t = decodeUtf8(trigger);
        const std::vector<uint32_t> e = decodeUtf8(expansion);
        funput_add_shortcut(engine_, t.data(), t.size(), e.data(), e.size());
    }

    // Feed one Unicode scalar tagged with its physical key source; a numpad digit
    // (source == KeySource::Numpad) is kept a literal number, not a VNI modifier.
    FunputResult process(uint32_t codepoint, KeySource source = KeySource::Standard) {
        return funput_process_key(engine_, codepoint, static_cast<uint32_t>(source));
    }
    FunputResult backspace() { return funput_backspace(engine_); }

    // Re-open an already-committed word as the live composition, so the next key
    // edits it. Returns whether it was taken: only a Vietnamese syllable is, which
    // is what keeps English words and URLs literal. Leave the document alone on
    // false — the engine has not taken ownership of anything.
    bool adopt(const std::string &word) {
        const std::vector<uint32_t> cps = decodeUtf8(word);
        return funput_adopt(engine_, cps.data(), cps.size());
    }

    // Flip the word being composed between its Vietnamese form and its raw keys.
    // Preedit shells re-render buffer() when the action is not ACTION_NONE.
    FunputResult flipComposing() { return funput_flip_composing(engine_); }

    // The composed (marked/underlined) buffer as UTF-8.
    std::string buffer() const {
        uint32_t cps[CHARS_CAP];
        uintptr_t n = funput_buffer(engine_, cps, CHARS_CAP);
        std::string out;
        for (uintptr_t i = 0; i < n; ++i) appendUtf8(out, cps[i]);
        return out;
    }

    // Decode a FunputResult's output codepoints (chars[0..count]) to UTF-8.
    static std::string output(const FunputResult &r) {
        std::string out;
        for (uint32_t i = 0; i < r.count; ++i) appendUtf8(out, r.chars[i]);
        return out;
    }

private:
    FunputEngine *engine_;
};

} // namespace funput

#endif // FUNPUT_FFI_HANDLE_H
