// [ExtraOnsetLetters] as the C ABI's `ONSET_*` letter mask for
// `funput_set_extra_onsets`. Letter by letter rather than a cast: the settings
// type's bits are private and are not the wire's, so the two cannot drift by
// accident. A letter added to [OnsetLetter] makes the `switch` below incomplete,
// which the build rejects (`-Werror=switch`, common/CMakeLists.txt).

#ifndef FUNPUT_FFI_ONSETS_H
#define FUNPUT_FFI_ONSETS_H

#include <cstdint>

#include "funput.h" // generated by cbindgen; on the include path via CMake
#include "settings/onsets/letters.h"

namespace funput {

inline uint8_t onsetWire(OnsetLetter letter) {
    switch (letter) {
    case OnsetLetter::Z: return ONSET_Z;
    case OnsetLetter::F: return ONSET_F;
    case OnsetLetter::W: return ONSET_W;
    case OnsetLetter::J: return ONSET_J;
    }
    return 0;
}

inline uint8_t onsetMask(ExtraOnsetLetters letters) {
    uint8_t mask = 0;
    for (OnsetLetter letter : kAllOnsetLetters) {
        if (letters.contains(letter)) mask = static_cast<uint8_t>(mask | onsetWire(letter));
    }
    return mask;
}

} // namespace funput

#endif // FUNPUT_FFI_ONSETS_H
